words_alpha_r = open("words_alpha.txt", "r")
words_alpha_r = words_alpha_r.read().splitlines()
print(f"Total words: {len(words_alpha_r)}")
print(f"Total 5 letter words: {len([word for word in words_alpha_r if len(word) == 5])}")
print(f"Total words longer than 7 letters: {len([word for word in words_alpha_r if len(word) > 6])}")
print(f"Total characters: {len([letter for word in words_alpha_r for letter in word])}")